### ISSUE TITLE
Expose prompt via config / UI

### ISSUE THREAD

**Issue by JamieKnight** [actually-useful-ai/alt-text-generator#1]
Hi,

First up, thanks for sharing this code base. It’s really nice to see examples of positive AI concepts in the open building on locally running tools. It’s extremely useful to see how apps like thing are structured and hosted :)

I’ve been having a look through the code and I was wondering if it would be possible to expose the [prompt](https://github.com/actually-useful-ai/alt-text-generator/blob/88c9c6223122438a5a564b642d3c984dcb3cf352/src/store/index.js#L114) used in the alt text generation process via a config value.

This would allow for fine tuning for specific use cases and help folks to understand how it works without needing to trace through the source code. 

I could imagine myself tuning the prompt with additional context to help the generator along. For example, ‘this image will be used on a homepage’ or ‘this image is part of a news article about someone who has recently died.’

Perhaps this could also be exposed in the UI somewhere to support easy experimentation and iteration without needing to restart the app. *

Thanks again for sharing this project and your experimentation. It’s a really valuable contribution to the accessibility community. We can’t determine if something is worthwhile unless folks take the time to explore it properly.

I hope you have a wonderful new year ahead :)

* for advanced local use cases, not for the hosted version as this would be a terrible security risk

**Comment by lukeslp** [comment]
Done & done! Good request! I had something like that in for testing, not sure why I removed it. Anyway - I relocated a few things under "advanced" at the bottom; prompt and model overrides are available there. Also added paste and made the detailed analysis more expressive.

![normal_alt](https://github.com/user-attachments/assets/9fd7ae73-c292-4737-acc1-bcebdcf94e3d)
![prompt_override](https://github.com/user-attachments/assets/07c482dc-6435-4fc5-86b6-c10b670c9d1a)
![detailed_process](https://github.com/user-attachments/assets/29e5eec8-d0de-4da4-a84a-cf16886c7c08)
![detailed_result](https://github.com/user-attachments/assets/9ab98c48-a5b5-4332-b018-6f711f0f9456)


Keep me posted. I have a few other things on my radar as time allows, like TTS; image downloads with the alt placed in the metadata; and it would be easy enough to put an API key input for people willing to use cloud LLMs, like huggingface would take two seconds. Debating that or giving a license key for my own cloud instance, which would be cheaper and easier for people ... decisions decisions.
